### ISSUE TITLE
key是可以用的，但是查询结果都是xx怎么回事？

### ISSUE THREAD

**Issue by guotao** [woodchen-ink/openai-billing-query#31]
![image](https://github.com/woodchen-ink/openai-billing-query/assets/46209/5ddc30de-9357-4847-8529-42b47864c6fa)

如果需要登录获取sess，那直接在openai后台看不就得了，而且怎么批量查呢？

**Comment by woodchen-ink** [comment]
sess14天有效期，有了之后保存下
多个sess换行
