### ISSUE TITLE
请问通过access token获取sess]失效了么

### ISSUE THREAD

**Issue by TiMi518** [woodchen-ink/openai-billing-query#32]
嗨

**Comment by BenedictKing** [comment]
可能是官方加了CORS验证？

**Comment by BenedictKing** [comment]
${apiUrl}/dashboard/onboarding/login 这个入口好像不让用户自己调用了

**Comment by mouxangithub** [comment]
你拿的怕是chat的access token吧和api的access token不是一起的，我想的是api的token有没有什么项目脚本或者api可以用账号密码去获取，chat的token现在有潘多拉等那些项目获取

**Comment by woodchen-ink** [comment]
使用新版，已修复。
可以通过pandora的access token来获取sess

**Comment by mouxangithub** [comment]
> 使用新版，已修复。 可以通过pandora的access token来获取sess

pandora拿的access token似乎是chat的，api的无法使用，拿不到see-

**Comment by woodchen-ink** [comment]
> > 使用新版，已修复。 可以通过pandora的access token来获取sess
> 
> pandora拿的access token似乎是chat的，api的无法使用，拿不到see-

你说的对，是我弄错了

**Comment by TiMi518** [comment]
我是想要通过潘多拉获取acess，然后通过这个acess获取sess

**Comment by mouxangithub** [comment]
> 我是想要通过潘多拉获取acess，然后通过这个acess获取sess

那这个你可以直接调潘多拉的api接口或者用这个项目[PandoraNext-TokensTool](https://github.com/Yanyutin753/PandoraNext-TokensTool)

**Comment by mouxangithub** [comment]
现在可以用潘多拉的proxy模式的/api/auth/platform/login获取了

**Comment by mouxangithub** [comment]
> > > 使用新版，已修复。 可以通过pandora的access token来获取sess
> > 
> > 
> > pandora拿的access token似乎是chat的，api的无法使用，拿不到see-
> 
> 你说的对，是我弄错了


现在可以用潘多拉的proxy模式的/api/auth/platform/login获取了

**Comment by woodchen-ink** [comment]
这里获取的access可以获取sess吗？有postman的示例可以看下吗？

**Comment by mouxangithub** [comment]
> 这里获取的access可以获取sess吗？有postman的示例可以看下吗？

是的，我尝试了生成的sess-xxx是可以直接调官方api v1进行请求的，而且还能查询余额等操作，文档地址：https://docs.pandoranext.com/api-ref/proxy/#%E8%8E%B7%E5%8F%96-sess-key

![a1ef9a7d2211350f3205bc98dba564f](https://github.com/woodchen-ink/openai-billing-query/assets/48978046/6b4c9f04-b39a-4ebd-bd7e-b7ab57448970)
![1bc37bdc6c51e2a3dd54c0d93bea7b7](https://github.com/woodchen-ink/openai-billing-query/assets/48978046/6c53bdb8-6436-4bbe-a603-80c27a3f0f1e)

**Comment by woodchen-ink** [comment]
我昨天晚上也看了文档，因为这几天弄了个服务器玩，就没更新这个。

不知道有没有好人提供下pandoranext的测试地址，我自己额度比较少，可以做成这样：

支持批量输入  邮箱，密码，MFA
换行分隔

3秒获取一个

当然如果能直接PR就更好了，新增个HTML，只需要改一下js就行

**Comment by mouxangithub** [comment]
> 我昨天晚上也看了文档，因为这几天弄了个服务器玩，就没更新这个。 不知道有没有好人提供下pandoranext的测试地址，我自己额度比较少，可以做成这样： 支持批量输入  邮箱，密码，MFA 换行分隔 3秒获取一个 当然如果能直接PR就更好了，新增个HTML，只需要改一下js就行

好的，我今晚尝试下直接用你的模板改写一个页面

**Comment by woodchen-ink** [comment]
tks

**Comment by BenedictKing** [comment]
> > 这里获取的access可以获取sess吗？有postman的示例可以看下吗？
> 
> 是的，我尝试了生成的sess-xxx是可以直接调官方api v1进行请求的，而且还能查询余额等操作，文档地址：https://docs.pandoranext.com/api-ref/proxy/#%E8%8E%B7%E5%8F%96-sess-key
> 
> ![a1ef9a7d2211350f3205bc98dba564f](https://private-user-images.githubusercontent.com/48978046/291761144-6b4c9f04-b39a-4ebd-bd7e-b7ab57448970.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwODIzNTIsIm5iZiI6MTcwMzA4MjA1MiwicGF0aCI6Ii80ODk3ODA0Ni8yOTE3NjExNDQtNmI0YzlmMDQtYjM5YS00ZWJkLWJkN2UtYjdhYjU3NDQ4OTcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDE0MjA1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4NjkwY2MyZjM5ODY5ZDE5ODJhNWYwYTk2Zjk0ZjgwZjk0MGQ3NTBkOTM3NDRkZTMyODI3YWIwN2M0N2JmM2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.y4dCWFgGseMPeAPMKKP2bUe-HI0J6I8JY9n02v7e37I) ![1bc37bdc6c51e2a3dd54c0d93bea7b7](https://private-user-images.githubusercontent.com/48978046/291761164-6c53bdb8-6436-4bbe-a603-80c27a3f0f1e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwODIzNTIsIm5iZiI6MTcwMzA4MjA1MiwicGF0aCI6Ii80ODk3ODA0Ni8yOTE3NjExNjQtNmM1M2JkYjgtNjQzNi00YmJlLWE2MDMtODBjMjdhM2YwZjFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDE0MjA1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlMTRkN2E5M2EwZWE3YjQ1ZjdmN2YzMzkzMmRlZjllZDliYmQ1Mjc0OTAyZWU0YTYzY2MyYzhhOTBhMTUzNjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CkwxV4ntgpkuNNNMqAjt4JtsehJ6dEB6KGgQVnNoIFw)

建议还是继续跟one-key集成，拿到的sess-key放到one-key中很好用

**Comment by woodchen-ink** [comment]
#35 此大哥PR已处理，使用新版即可通过pandora获取sess

**Comment by mouxangithub** [comment]
手动快速从platform中抓取token等信息的脚本，使用方法：登录platform后打开F12开发者工具，打开控制台或者console，输入下面的代码就会出现一系列的token等信息，然后自行复制

```shell
// 手动从localStorage中获取token等相关信息
Object.keys(localStorage).forEach(function(key) {
  var value = localStorage.getItem(key);
  function timestampToTime(timestamp) {
    // 创建一个新的 Date 对象，将时间戳传递给构造函数
    var date = new Date(timestamp * 1000); // 乘以 1000 转换为毫秒
  
    // 获取日期和时间的各个部分
    var year = date.getFullYear();
    var month = date.getMonth() + 1; // 月份是从 0 开始的，所以要加 1
    var day = date.getDate();
    var hours = date.getHours();
    var minutes = date.getMinutes();
    var seconds = date.getSeconds();
  
    // 格式化日期和时间
    var formattedTime = `${year}-${month.toString().padStart(2, '0')}-${day.toString().padStart(2, '0')} ${hours.toString().padStart(2, '0')}:${minutes.toString().padStart(2, '0')}:${seconds.toString().padStart(2, '0')}`;
  
    return formattedTime;
  }
  var datas = JSON.parse(value);
  if(datas && datas.body && datas.body.refresh_token) {
    console.log("================================")
    console.log(`id_token: ${datas.body.id_token}`);
    console.log(`client_id: ${datas.body.client_id}`);
    console.log(`access_token: ${datas.body.access_token}`);
    console.log(`refresh_token: ${datas.body.refresh_token}`);
    console.log(`token_type: ${datas.body.token_type}`);
    console.log(`decodedToken: `, datas.body.decodedToken);
    console.log(`有效期: ${datas.body.expires_in / (60 * 60 * 24)}天`);
    console.log(`到期时间: ${timestampToTime(datas.expiresAt)}`);
    console.log("================================")
  }
});
```

**Comment by woodchen-ink** [comment]
这个issue先关了。
